# Generated by Django 3.2.3 on 2021-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_drink",
                    models.CharField(max_length=200, verbose_name="Name drink"),
                ),
                ("drink_url", models.TextField(verbose_name="Url drink img")),
                ("instruction", models.TextField(verbose_name="Instruction")),
                (
                    "ingredients",
                    models.CharField(max_length=300, verbose_name="Ingredients"),
                ),
                ("measures", models.CharField(max_length=300, verbose_name="Measures")),
            ],
        ),
    ]
