# Generated by Django 3.2.4 on 2021-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0007_rename_name_drink_drink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_property',
            field=models.CharField(max_length=50, null=True, verbose_name='Drink property'),
        ),
    ]
