# Generated by Django 3.2.4 on 2021-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0008_drink_drink_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drink_property',
        ),
        migrations.AddField(
            model_name='drink',
            name='random_drink',
            field=models.BooleanField(default=bool),
            preserve_default=False,
        ),
    ]
