# Generated by Django 3.2.4 on 2021-09-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0009_auto_20210908_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='random_drink',
            new_name='is_alcoholic',
        ),
    ]
